import { playerName } from "../game/selectors";
import { Screen } from "./Layout";
import { WinnerCelebration } from "./WinnerCelebration";

export const RevealView = ({ session, round, onNext }) => {
  const winner = round.submissions.find((s) => s.id === round.winnerSubmissionId);

  if (!winner || round.revealCursor > 0) {
    return (
      <Screen
        className="phase-screen phase-screen--reveal"
        title="Winner reveal complete"
        subtitle="Points locked. Let’s hit the round scoreboard."
        actions={<button onClick={onNext}>Show round scoreboard</button>}
      />
    );
  }

  return (
    <Screen
      className="phase-screen phase-screen--reveal"
      title="🏆 Round Winner"
      subtitle={`${playerName(session, winner.playerId)} wins with: ${winner.text}`}
      actions={<button onClick={onNext}>Continue</button>}
    >
      <WinnerCelebration winnerName={playerName(session, winner.playerId)} />
      <article className="card reveal winner-reveal-card">
        <p>{winner.generatedScene || "Generating..."}</p>
        {winner.mediaUrl ? (
          <div className="video-wrap">
            {winner.mediaType === "image" ? (
              <img className="scene-image" src={winner.mediaUrl} alt="Generated scene" />
            ) : (
              <video className="scene-video" src={winner.mediaUrl} controls autoPlay muted playsInline />
            )}
            <small>
              Generated by {winner.mediaProvider || (winner.mediaType === "image" ? "imagen-mock" : "veo3-mock")}{winner.fallback ? " (demo)" : ""}
            </small>
          </div>
        ) : null}
        <small>Status: {winner.safetyStatus}</small>
      </article>
    </Screen>
  );
};
