import { playerName } from "../game/selectors";
import { Screen } from "./Layout";

export const RevealView = ({ session, round, onNext }) => {
  const winner = round.submissions.find((s) => s.id === round.winnerSubmissionId);

  if (!winner || round.revealCursor > 0) {
    return (
      <Screen
        title="Winner reveal complete"
        subtitle="Points locked. Let’s hit the round scoreboard."
        actions={<button onClick={onNext}>Show round scoreboard</button>}
      />
    );
  }

  return (
    <Screen
      title="🏆 Round Winner"
      subtitle={`${playerName(session, winner.playerId)} wins with: ${winner.text}`}
      actions={<button onClick={onNext}>Continue</button>}
    >
      <article className="card reveal">
        <p>{winner.generatedScene || "Generating..."}</p>
        {winner.videoUrl ? (
          <div className="video-wrap">
            <video className="scene-video" src={winner.videoUrl} controls autoPlay muted playsInline />
            <small>Generated by {winner.videoProvider || "veo3-mock"} (demo clip)</small>
          </div>
        ) : null}
        <small>Status: {winner.safetyStatus}</small>
      </article>
    </Screen>
  );
};
