import { useEffect, useMemo, useState } from "react";
import { playerName } from "../game/selectors";
import { Screen } from "./Layout";

export const VoteView = ({ session, me, round, onVote, onFinishVoting }) => {
  const [showcaseIndex, setShowcaseIndex] = useState(0);
  const [phase, setPhase] = useState("showcase");
  const [seconds, setSeconds] = useState(session.settings.voteSeconds || 20);

  useEffect(() => {
    setShowcaseIndex(0);
    setPhase("showcase");
    setSeconds(session.settings.voteSeconds || 20);
  }, [round.id, session.settings.voteSeconds]);

  useEffect(() => {
    if (phase !== "voting") return;
    const timer = setInterval(() => setSeconds((s) => Math.max(0, s - 1)), 1000);
    return () => clearInterval(timer);
  }, [phase]);

  useEffect(() => {
    if (phase === "voting" && seconds === 0 && me.isHost) {
      onFinishVoting();
    }
  }, [phase, seconds, me.isHost, onFinishVoting]);

  const mySubmission = round.submissions.find((s) => s.playerId === me.id);
  const myVote = round.votes.find((v) => v.voterId === me.id);

  const showcaseDone = showcaseIndex >= round.submissions.length;
  const active = round.submissions[showcaseIndex];

  const timerClass = useMemo(() => {
    if (seconds <= 6) return "timer-urgent";
    if (seconds <= 12) return "timer-warning";
    return "timer-normal";
  }, [seconds]);

  const showcaseProgress = ((showcaseIndex + 1) / round.submissions.length) * 100;

  if (phase === "showcase" && !showcaseDone) {
    return (
      <Screen
        title={`Watch clips ${showcaseIndex + 1}/${round.submissions.length}`}
        subtitle="Watch every generated video before voting opens"
        actions={
          <>
            <button onClick={() => setShowcaseIndex((i) => i + 1)}>Skip / Next</button>
            {showcaseIndex === round.submissions.length - 1 ? (
              <button onClick={() => setPhase("voting")}>Start voting</button>
            ) : null}
          </>
        }
      >
        <article className="card reveal vote-showcase">
          <div className="showcase-progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow={showcaseProgress}>
            <div className="showcase-progress__bar" style={{ width: `${showcaseProgress}%` }} />
          </div>

          <div className="video-stage">
            <video
              key={`${active.id}-${showcaseIndex}`}
              className="scene-video"
              src={active.videoUrl}
              controls
              autoPlay
              muted
              playsInline
              onEnded={() => setShowcaseIndex((i) => Math.min(i + 1, round.submissions.length))}
            />
            <div className="video-overlay">
              <span className="video-overlay__player">{playerName(session, active.playerId)}</span>
              <span className="video-overlay__index">Clip {showcaseIndex + 1}/{round.submissions.length}</span>
            </div>
          </div>

          <p className="clip-prompt">Prompt: {active.text}</p>
          <small>Generated by {active.videoProvider || "veo3-mock"} (demo clip)</small>
        </article>
      </Screen>
    );
  }

  if (phase === "showcase" && showcaseDone) {
    return (
      <Screen
        title="Showcase complete"
        subtitle="All clips shown. Time to vote."
        actions={<button onClick={() => setPhase("voting")}>Open voting</button>}
      />
    );
  }

  return (
    <Screen
      title="Vote for your favorite"
      subtitle="One vote. No self-votes. Choose wisely, chaos goblin."
      actions={me.isHost ? <button onClick={onFinishVoting}>Close voting now</button> : null}
    >
      <div className={`timer ${timerClass}`}>
        <div className="timer-circle" style={{ "--progress": `${(seconds / (session.settings.voteSeconds || 20)) * 100}%` }}>
          <span className="timer-value">{seconds}</span>
        </div>
        <span className="timer-label">voting seconds</span>
      </div>

      <div className="card">
        <ul className="clean-list spaced">
          {round.submissions.map((submission) => {
            const disabled = submission.id === mySubmission?.id;
            const selected = myVote?.submissionId === submission.id;
            return (
              <li key={submission.id}>
                <button
                  disabled={disabled}
                  className={`mobile-vote-option ${selected ? "selected" : ""}`}
                  onClick={() => onVote(submission.id)}
                >
                  <span className="mobile-vote-content">
                    <span className="mobile-vote-answer">{submission.generatedScene}</span>
                    <span className="mobile-vote-author">{disabled ? "Your entry" : "Tap to vote"}</span>
                  </span>
                  <span className="mobile-vote-check">✓</span>
                </button>
              </li>
            );
          })}
        </ul>
      </div>
    </Screen>
  );
};
