import { useEffect, useMemo, useState } from "react";
import { playerName } from "../game/selectors";
import { Screen } from "./Layout";

export const VoteView = ({
  session,
  me,
  round,
  onVote,
  onFinishVoting,
  onNextClip,
  onStartVoting,
}) => {
  const [seconds, setSeconds] = useState(session.settings.voteSeconds || 20);

  useEffect(() => {
    if (round.votePhase !== "voting") {
      setSeconds(session.settings.voteSeconds || 20);
      return;
    }

    const tick = () => {
      const remaining = Math.max(0, Math.ceil(((round.voteEndsAt || Date.now()) - Date.now()) / 1000));
      setSeconds(remaining);
      if (remaining === 0 && me.isHost) onFinishVoting();
    };

    tick();
    const timer = setInterval(tick, 1000);
    return () => clearInterval(timer);
  }, [round.votePhase, round.voteEndsAt, session.settings.voteSeconds, me.isHost, onFinishVoting]);

  const nonHostIds = useMemo(
    () => new Set(session.players.filter((p) => !p.isHost).map((p) => p.id)),
    [session.players]
  );

  const playableSubmissions = useMemo(
    () => round.submissions.filter((s) => nonHostIds.has(s.playerId)),
    [round.submissions, nonHostIds]
  );

  const mySubmission = playableSubmissions.find((s) => s.playerId === me.id);
  const myVote = round.votes.find((v) => v.voterId === me.id);

  const showcaseIndex = round.showcaseIndex || 0;
  const showcaseDone = showcaseIndex >= playableSubmissions.length;
  const active = playableSubmissions[showcaseIndex];

  const timerClass = useMemo(() => {
    if (seconds <= 6) return "timer-urgent";
    if (seconds <= 12) return "timer-warning";
    return "timer-normal";
  }, [seconds]);

  useEffect(() => {
    if (!me.isHost) return;
    if (round.votePhase !== "showcase") return;
    if (!showcaseDone) return;
    onStartVoting();
  }, [me.isHost, round.votePhase, showcaseDone, onStartVoting]);

  const showcaseProgress = playableSubmissions.length
    ? ((Math.min(showcaseIndex + 1, playableSubmissions.length)) / playableSubmissions.length) * 100
    : 0;

  if (round.votePhase === "showcase" && !showcaseDone) {
    return (
      <Screen
        className="phase-screen phase-screen--vote phase-screen--showcase"
        title={`Watch clips ${showcaseIndex + 1}/${playableSubmissions.length}`}
        subtitle="Watch every generated video before voting opens"
        actions={
          me.isHost ? (
            <>
              <button onClick={onNextClip}>Skip / Next</button>
              {showcaseIndex === playableSubmissions.length - 1 ? (
                <button onClick={onStartVoting}>Start voting</button>
              ) : null}
            </>
          ) : (
            <p>Host is controlling showcase…</p>
          )
        }
      >
        <article className="card reveal vote-showcase">
          <div
            className="showcase-progress"
            role="progressbar"
            aria-valuemin="0"
            aria-valuemax="100"
            aria-valuenow={showcaseProgress}
          >
            <div className="showcase-progress__bar" style={{ width: `${showcaseProgress}%` }} />
          </div>

          <div className="video-stage">
            {active.mediaType === "image" ? (
              <img className="scene-image" src={active.mediaUrl} alt="Generated showcase scene" />
            ) : (
              <video
                key={`${active.id}-${showcaseIndex}`}
                className="scene-video"
                src={active.mediaUrl}
                controls
                autoPlay
                muted
                playsInline
                onEnded={() => me.isHost && onNextClip()}
              />
            )}
            <div className="video-overlay">
              <span className="video-overlay__player">{playerName(session, active.playerId)}</span>
              <span className="video-overlay__index">
                Clip {showcaseIndex + 1}/{playableSubmissions.length}
              </span>
            </div>
          </div>

          <p className="clip-prompt">Twist: {active.text}</p>
          <small>
            Generated by {active.mediaProvider || (active.mediaType === "image" ? "imagen-mock" : "veo3-mock")}{active.fallback ? " (demo)" : ""}
          </small>
        </article>
      </Screen>
    );
  }

  if (round.votePhase === "showcase" && showcaseDone) {
    return (
      <Screen
        className="phase-screen phase-screen--vote phase-screen--showcase"
        title="Showcase complete"
        subtitle="All clips shown. Waiting for host to open voting."
        actions={me.isHost ? <button onClick={onStartVoting}>Open voting</button> : null}
      />
    );
  }

  return (
    <Screen
      className="phase-screen phase-screen--vote"
      title="Vote for your favorite"
      subtitle="One vote. No self-votes. Choose wisely, chaos goblin."
      actions={me.isHost ? <button onClick={onFinishVoting}>Close voting now</button> : null}
    >
      <div className={`timer ${timerClass}`}>
        <div
          className="timer-circle"
          style={{
            "--progress": `${(seconds / (session.settings.voteSeconds || 20)) * 100}%`,
          }}
        >
          <span className="timer-value">{seconds}</span>
        </div>
        <span className="timer-label">voting seconds</span>
      </div>

      <div className="card vote-options-card">
        <ul className="clean-list spaced">
          {playableSubmissions.map((submission) => {
            const disabled = submission.id === mySubmission?.id;
            const selected = myVote?.submissionId === submission.id;
            return (
              <li key={submission.id}>
                <button
                  disabled={disabled}
                  className={`mobile-vote-option ${selected ? "selected" : ""}`}
                  onClick={() => onVote(submission.id)}
                >
                  <span className="mobile-vote-content">
                    <span className="mobile-vote-answer">{submission.generatedScene}</span>
                    <span className="mobile-vote-author">
                      {disabled ? "Your entry" : "Tap to vote"}
                    </span>
                  </span>
                  <span className="mobile-vote-check">✓</span>
                </button>
              </li>
            );
          })}
        </ul>
      </div>
    </Screen>
  );
};
